### ISSUE TITLE
Don't use `ssh-keyscan` before connecting

### ISSUE THREAD

**Issue by rinkp** [JustSamuel/dispuutivv#2]
Doing a ssh-keyscan first and then connecting is as bad as not verifying the keys at all

You want to be notified in case those host keys change (and that should not happen [unexpectedly as for github.com](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/)), so you should consider setting them in action variables (can be public) or ask the CBC to publish SSHFP records (similar to what is done for files01)

Current keys: 
```
# webhost.gewis.nl
webhost.gewis.nl ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaS7GVAQvQlZlqz1wEN9PdIC/DnfX9jXbjpLko9q6i2bB0ceCv0tJexynToDgRdGKd/ALF8kALr6uNQ98LU+mDGZGWI+BFg6HS6mp/zmZIrkigVyoFQhR6U1c14RyG63w1NFGXbAt6dPwAehqAXrxz5sCn5NJaMOldSmEkNYmG7Mu8WDaVjLUS7QVJA50EYW+wqK6w4khO/3TBZvXl2lyHykSoQ0m4g9oXjzm7MGVOCzrk1463xEG0DGYVZJfVfKKBYDq2Mlb0/ruy6T6heM+Og2zr6cwOgevGcVAbvL+Hh99Zf1frxqs/+cmWc5OTI9QNY4tIb6S8B7QigasTHh7uTso3UI1A5EqdwdGPUE0Ta5GjaqtNhRd8klVFXYw3zQ5sq7yRv4VpxH03STOjBxKdGvXKwubUTxCybZNY2EOA2cMD39bqgmX8o+CBDkUgqVMJ2X/1whPGbw5vERDXqjZO8+G7tHKfBJ3NIq169OwWVbR5Lcu3WHyMgqw+FOV2Cnk=
webhost.gewis.nl ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHhW3PGsTBvaZwPSjwcnkbO4AgZGhvHlJcnpPkEjxLUgfE2XdWeaEY1mtyZ1wp1mxnCrZzbIyrY8+tLrRoJVR84=
webhost.gewis.nl ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN6gM0CojAcA/wv0LytELxZY6b4ExaTiNHWYENCrVmdm
```

https://github.com/JustSamuel/dispuutivv/blob/5de7f5fea6a1093d74b7ded815c8144cd1689706/.github/workflows/node.js.yml#L51C23-L51C23

**Comment by JustSamuel** [comment]
Thanks for the heads-up. This has been resolved.
